# Generated by Django 3.2.5 on 2021-07-06 17:58

import User.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='Avatar/default.png', upload_to=User.models.UserProfile.upload_avatar_to, verbose_name='avatar'),
        ),
    ]
